"""initial schema

Revision ID: 4fc42cf74e17
Revises:
Create Date: 2026-08-16 05:25:29.880213

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fc42cf74e17"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("theme", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("base_currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("last_pay_method", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("rates_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_verifications_email"), "email_verifications", ["email"], unique=False)
    op.create_table(
        "splits",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "mode", sa.Enum("equal", "shares", "exact", name="splitmode", native_enum=False, length=20), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "member", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sessions_invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "kind", sa.Enum("personal", "joint", name="accountkind", native_enum=False, length=20), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_book_id"), "accounts", ["book_id"], unique=False)
    op.create_table(
        "book_members",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("book_id", "user_id"),
    )
    op.create_table(
        "currency_rates",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("book_id", "code"),
    )
    op.create_table(
        "ledgers",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("emoji", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column(
            "kind", sa.Enum("household", "trip", name="ledgerkind", native_enum=False, length=20), nullable=False
        ),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ledgers_book_id"), "ledgers", ["book_id"], unique=False)
    op.create_table(
        "people",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("emoji", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_book_id"), "people", ["book_id"], unique=False)
    op.create_table(
        "account_ownership",
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("person_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("share", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
        ),
        sa.PrimaryKeyConstraint("account_id", "person_id"),
    )
    op.create_table(
        "expenses",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("ledger_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("emoji", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("planned", sa.Boolean(), nullable=False),
        sa.Column("split_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["split_id"],
            ["splits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_date"), "expenses", ["date"], unique=False)
    op.create_index(op.f("ix_expenses_ledger_id"), "expenses", ["ledger_id"], unique=False)
    op.create_table(
        "rules",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("ledger_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("emoji", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "monthly",
                "bimonthly",
                "quarterly",
                "semiannual",
                "yearly",
                name="frequency",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("due_day", sa.Integer(), nullable=False),
        sa.Column("start_month", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
        sa.Column("end_month", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("split_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["split_id"],
            ["splits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rules_ledger_id"), "rules", ["ledger_id"], unique=False)
    op.create_table(
        "settlements",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("ledger_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("from_person_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("to_person_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_person_id"],
            ["people.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_person_id"],
            ["people.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_settlements_date"), "settlements", ["date"], unique=False)
    op.create_index(op.f("ix_settlements_ledger_id"), "settlements", ["ledger_id"], unique=False)
    op.create_table(
        "split_shares",
        sa.Column("split_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("person_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
        ),
        sa.ForeignKeyConstraint(
            ["split_id"],
            ["splits.id"],
        ),
        sa.PrimaryKeyConstraint("split_id", "person_id"),
    )
    op.create_table(
        "rule_overrides",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("rule_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("period", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("split_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["split_id"],
            ["splits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "period", name="uq_rule_overrides_rule_period"),
    )
    op.create_index(op.f("ix_rule_overrides_rule_id"), "rule_overrides", ["rule_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rule_overrides_rule_id"), table_name="rule_overrides")
    op.drop_table("rule_overrides")
    op.drop_table("split_shares")
    op.drop_index(op.f("ix_settlements_ledger_id"), table_name="settlements")
    op.drop_index(op.f("ix_settlements_date"), table_name="settlements")
    op.drop_table("settlements")
    op.drop_index(op.f("ix_rules_ledger_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_expenses_ledger_id"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_date"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_table("account_ownership")
    op.drop_index(op.f("ix_people_book_id"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_ledgers_book_id"), table_name="ledgers")
    op.drop_table("ledgers")
    op.drop_table("currency_rates")
    op.drop_table("book_members")
    op.drop_index(op.f("ix_accounts_book_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("splits")
    op.drop_index(op.f("ix_email_verifications_email"), table_name="email_verifications")
    op.drop_table("email_verifications")
    op.drop_table("books")
    # ### end Alembic commands ###
