"""settlement items

Revision ID: 8e650f41c4c4
Revises: 72153a5e748c
Create Date: 2026-08-16 20:20:05.379103

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e650f41c4c4"
down_revision: str | None = "72153a5e748c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settlement_items",
        sa.Column("settlement_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(length=72), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
        ),
        sa.PrimaryKeyConstraint("settlement_id", "item_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settlement_items")
    # ### end Alembic commands ###
