"""book sharing: members, invites, snapshots

Revision ID: 72153a5e748c
Revises: 4fc42cf74e17
Create Date: 2026-08-16 18:47:01.356797

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72153a5e748c"
down_revision: str | None = "4fc42cf74e17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_invites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_book_invites_book_id"), "book_invites", ["book_id"], unique=False)
    op.create_index(op.f("ix_book_invites_code"), "book_invites", ["code"], unique=True)
    op.create_table(
        "book_snapshots",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("book_id", "version"),
    )
    # Added with a server_default so existing rows can satisfy NOT NULL, then
    # dropped again so the final schema matches the models exactly. Every
    # membership that predates sharing is a book's creator, hence 'owner'.
    op.add_column(
        "book_members",
        sa.Column(
            "role",
            sa.Enum("owner", "member", name="memberrole", native_enum=False, length=20),
            nullable=False,
            server_default="owner",
        ),
    )
    op.alter_column("book_members", "role", server_default=None)
    op.add_column("book_members", sa.Column("person_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column("books", sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
    op.alter_column("books", "version", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "version")
    op.drop_column("book_members", "person_id")
    op.drop_column("book_members", "role")
    op.drop_table("book_snapshots")
    op.drop_index(op.f("ix_book_invites_code"), table_name="book_invites")
    op.drop_index(op.f("ix_book_invites_book_id"), table_name="book_invites")
    op.drop_table("book_invites")
    # ### end Alembic commands ###
